---
title: "OSW Exec Summary"
author: "Morgan Browning"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)

# Sourcing
source("osw_Scripts/osw_setup.R")
source("osw_Scripts/osw_data.R")
source("osw_Scripts/osw_results.R")
```

Objective
=======================================================================

Row
-----------------------------------------------------------------------

### Primary Questions

1. How do costs and emisisons constraints affect offshore wind's place in the US grid mix?
2. Which combinattions of factors elicit the largest amount of offshore wind?
3. How do these factors affect when and how quickly offshore wind is built?
4. What are the air quality and emissions benefits that offshore wind can yield?

Row
-----------------------------------------------------------------------

### Methodology

* Modeling
  + Nested parametric sensitivity analysis
* Data prep
  + Results export
  + Summary Tables - Regional and Nationwide
* Results Analysis
  + Graphical Analysis
  + Correlation (possible LR?)

Scenarios
=======================================================================

Row
-----------------------------------------------------------------------

### Cost Curves

```{r}
ggplotly(costscen_col)
```

Row
-----------------------------------------------------------------------

### Emissions Caps

```{r}
ggplotly(emissionsscen_col)
```

OSW
=======================================================================

Row
-----------------------------------------------------------------------

### Cumulative Capacity

```{r}
ggplotly(cap_col_side)
```

### New Capacity

```{r}
ggplotly(newcap_col_top)
```

Row
-----------------------------------------------------------------------

### 2050 Installed Capacity

```{r}
cap_2050_table
```



